# Generated by Django 4.2.3 on 2023-08-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0002_rename_updates_at_advert_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advert',
            table='advertisements',
        ),
    ]
