# Generated by Django 4.2.3 on 2023-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0005_advert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(default='media\x07dverts\\kosmos-76-foto-66.jpg', upload_to='adverts/', verbose_name='Изображение'),
        ),
    ]
