# Generated by Django 4.2.3 on 2023-08-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0010_alter_advert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(default='adverts/adv.png', upload_to='adverts/', verbose_name='Изображение'),
        ),
    ]
